

name: API Tes Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # Runs twice: daily at 2 AM UTC and Monday/Thursday at 2 PM UTC
   # - cron: '0 2 * * *'     # Daily at 2 AM UTC
   - cron: '0 14 * * 1,4'  # Monday and Thursday at 2 PM UTC
  workflow_dispatch:  # Allows manual trigger from GitHub UI
       

                    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Execute Test
      run: mvn clean test -Dsuite=testng 

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
       name: Logs
       path: logs/

   
